import SiteImage from '@/components/SiteImage';

export default function HoneypotsPage() {
  return (
    <main className="max-w-6xl mx-auto px-6 py-16 space-y-16">
      <h1 className="text-4xl font-bold mb-4">Honeypot Indicators</h1>

      <p className="text-gray-300 max-w-3xl leading-relaxed">
        Electrum Observatory uses a structured heuristic framework to identify Electrum
        servers that may exhibit surveillance characteristics, modified protocol behavior,
        or honeypot-like traits.  
        These indicators are <strong>signals</strong>, not definitive proof — but when
        combined, they can strongly suggest intentional monitoring or centralized control.
      </p>

      {/* ---------------------------------------------------------------------- */}
      {/* 1. CERTIFICATE-BASED INDICATORS */}
      {/* ---------------------------------------------------------------------- */}

      <section>
        <h2 className="text-3xl font-semibold mb-6">1. Certificate-Based Indicators</h2>

        <p className="text-gray-400 max-w-3xl mb-8">
          TLS certificates act as a cryptographic identity for Electrum servers.  
          Because most Electrum communication occurs over SSL/TLS, certificate patterns
          often reveal the true operator behind a cluster of servers.  
          Several certificate anomalies are strong signs of non-standard or suspicious deployments.
        </p>

        {/* ----------------------- 1.1 Certificate Reuse ----------------------- */}
        <div className="space-y-3">
          <h3 className="text-2xl font-semibold">1.1 Certificate Reuse Across Many Hosts</h3>

          <p className="text-gray-400 max-w-3xl">
            When the same TLS certificate is used across <strong>multiple IPs, different
            countries, unrelated ASNs, and independent hosting providers</strong>,
            it indicates that all those servers are controlled by a single operator.
          </p>

          <h4 className="text-xl font-semibold mt-3">Why this is suspicious</h4>
          <p className="text-gray-400 max-w-3xl">
            Legitimate community servers usually use short-lived certificates issued
            automatically by Let's Encrypt.  
            Reuse of the same certificate across many servers enables:
          </p>

          <ul className="text-gray-400 list-disc ml-6 space-y-1">
            <li>cross-server correlation of user traffic</li>
            <li>xpub or address-based re-identification</li>
            <li>fingerprinting of poll frequency</li>
            <li>network-wide identity tracking</li>
          </ul>

          {/* Optional future image */}
          {/* 
          <Image
            src="/honeypots/cert_reuse_example.png"
            alt="Certificate reuse pattern"
            width={900}
            height={500}
            className="rounded-lg border border-white/10 mt-4"
          />
          */}
        </div>

        {/* ----------------------- 1.2 Suspicious Issuer ----------------------- */}
        <div className="space-y-3 mt-10">
          <h3 className="text-2xl font-semibold">1.2 Suspicious Issuer or Internal CA</h3>

          <p className="text-gray-400 max-w-3xl">
            Certificates signed by enterprise interception appliances — such as Palo Alto,
            Blue Coat, Fortinet, or unknown internal CAs — are highly unusual for public
            Electrum servers.
          </p>

          <h4 className="text-xl font-semibold mt-3">Why this matters</h4>
          <p className="text-gray-400 max-w-3xl">
            Internal enterprise CAs are used for:
          </p>

          <ul className="text-gray-400 list-disc ml-6 space-y-1">
            <li>TLS interception</li>
            <li>payload inspection</li>
            <li>traffic logging</li>
            <li>identity correlation</li>
          </ul>
        </div>

        {/* ----------------------- 1.3 Long-Lived Certs ----------------------- */}
        <div className="space-y-3 mt-10">
          <h3 className="text-2xl font-semibold">1.3 Long-Lifetime Certificates</h3>

          <p className="text-gray-400 max-w-3xl">
            Certificates valid for <strong>10–30+ years</strong> are atypical and
            often generated by automated honeypots or “set-and-forget” monitoring nodes.
          </p>

          <h4 className="text-xl font-semibold mt-3">Why this is important</h4>
          <p className="text-gray-400 max-w-3xl">
            Long-lived certs make long-term tracking trivial:
          </p>

          <ul className="text-gray-400 list-disc ml-6 space-y-1">
            <li>no rotation → consistent fingerprint</li>
            <li>easier user correlation</li>
            <li>persistent identity tracking</li>
          </ul>
        </div>
      </section>

      {/* ---------------------------------------------------------------------- */}
      {/* 2. BEHAVIORAL INDICATORS */}
      {/* ---------------------------------------------------------------------- */}

      <section>
        <h2 className="text-3xl font-semibold mb-6">2. Behavioral Indicators</h2>

        <p className="text-gray-400 max-w-3xl mb-8">
          Modifications in response structure, timing, or protocol consistency can reveal
          servers designed for fingerprinting, logging, or analytics.
        </p>

        {/* 2.1 JSON Inconsistencies */}
        <div className="space-y-3">
          <h3 className="text-2xl font-semibold">2.1 Modified or Inconsistent JSON Responses</h3>

          <p className="text-gray-400 max-w-3xl">
            ElectrumX, Electrs, and Fulcrum produce stable, deterministic JSON.
            When a server deviates — adding fields, altering types, changing key order —
            it strongly suggests a custom fork or monitoring middleware.
          </p>
        </div>

        {/* 2.2 Timing anomalies */}
        <div className="space-y-3 mt-10">
          <h3 className="text-2xl font-semibold">2.2 Timing Anomalies</h3>

          <p className="text-gray-400 max-w-3xl">
            If latency spikes only for <strong>xpub</strong> or <strong>history</strong> queries,
            it may indicate logging or fingerprinting triggered by specific request types.
          </p>
        </div>

        {/* 2.3 Selective rate limiting */}
        <div className="space-y-3 mt-10">
          <h3 className="text-2xl font-semibold">2.3 Selective Rate Limiting</h3>

          <p className="text-gray-400 max-w-3xl">
            Honeypots and analytics servers often apply rate limits only to scanning-like
            traffic, not regular wallet usage.
          </p>
        </div>
      </section>

      {/* ---------------------------------------------------------------------- */}
      {/* 3. INFRASTRUCTURE INDICATORS */}
      {/* ---------------------------------------------------------------------- */}

      <section>
        <h2 className="text-3xl font-semibold mb-6">3. Infrastructure Indicators</h2>

        {/* 3.1 Perfect uptime */}
        <div className="space-y-3">
          <h3 className="text-2xl font-semibold">3.1 Perfect or Near-Perfect Uptime</h3>

          <p className="text-gray-400 max-w-3xl">
            Community servers naturally reboot or fail occasionally.  
            Surveillance-operated clusters often run with uptime &gt;99.99% on redundant hosts.
          </p>
        </div>

        {/* 3.2 ASN concentration */}
        <div className="space-y-3 mt-10">
          <h3 className="text-2xl font-semibold">3.2 Concentration in ASNs or Hosting Providers</h3>

          <p className="text-gray-400 max-w-3xl">
            When many servers share the same ASN, subnet, or hostname pattern, it usually
            means a single coordinated operator — often analytics firms or research groups.
          </p>
        </div>

        {/* 3.3 Tor exit hosting */}
        <div className="space-y-3 mt-10">
          <h3 className="text-2xl font-semibold">3.3 TOR Exit Node Hosting</h3>

          <p className="text-gray-400 max-w-3xl">
            Servers hosted on TOR exits with ephemeral IPs are difficult to attribute and
            commonly used for scanning or surveillance operations.
          </p>
        </div>
      </section>

      {/* ---------------------------------------------------------------------- */}
      {/* 4. QUERY HANDLING INDICATORS */}
      {/* ---------------------------------------------------------------------- */}

      <section>
        <h2 className="text-3xl font-semibold mb-6">4. Query-Handling & Fingerprinting Indicators</h2>

        {/* 4.1 Client discrimination */}
        <div className="space-y-3">
          <h3 className="text-2xl font-semibold">4.1 Discriminatory Responses by Client Type</h3>

          <p className="text-gray-400 max-w-3xl">
            Servers that behave differently depending on your claimed Electrum version or your
            request ordering are likely attempting active client fingerprinting.
          </p>
        </div>

        {/* 4.2 Address-type discrimination */}
        <div className="space-y-3 mt-10">
          <h3 className="text-2xl font-semibold">4.2 Address-Type Discrimination</h3>

          <p className="text-gray-400 max-w-3xl">
            Differentiated behavior for Taproot or SegWit addresses may reveal selective
            logging or specialized monitoring logic.
          </p>
        </div>

        {/* 4.3 Fingerprinting behavior */}
        <div className="space-y-3 mt-10">
          <h3 className="text-2xl font-semibold">4.3 Fingerprinting Behavior</h3>

          <p className="text-gray-400 max-w-3xl">
            These include timing variation tests, error-message differentiation, and subtle
            response modifications designed to classify scanners vs. real wallets.
          </p>
        </div>
      </section>

      {/* ---------------------------------------------------------------------- */}
      {/* 5. RISK SCORE */}
      {/* ---------------------------------------------------------------------- */}

      <section>
        <h2 className="text-3xl font-semibold mb-4">5. Honeypot Suspicion Score (HSS)</h2>

        <p className="text-gray-300 max-w-3xl mb-6">
          Servers receive a cumulative score across four axes.  
          The final score reflects the server's likelihood of operating as a monitoring node
          or analytics honeypot.
        </p>

        <ul className="text-gray-400 space-y-2 list-disc ml-6">
          <li><strong>TLS Axis:</strong> reused certs, self-signed certs, unusual issuers</li>
          <li><strong>Behavior Axis:</strong> timing anomalies, JSON deviations</li>
          <li><strong>Infrastructure Axis:</strong> hosting clusters, TOR behavior, uptime</li>
          <li><strong>Query Handling Axis:</strong> fingerprinting, selective failure</li>
        </ul>

        <p className="text-gray-400 mt-4">
          <strong>0–30</strong> LOW RISK  
          <br />
          <strong>31–69</strong> MEDIUM RISK  
          <br />
          <strong>70–100</strong> HIGH RISK — candidate for deeper forensic analysis.
        </p>

        <div className="mt-6 p-5 mx-auto md:mx-0 bg-white/5 border w-fit border-white/10 rounded-xl text-gray-400 italic">
          <SiteImage
            src="/results/honeypot_score.png"
            alt="Honeypot score JSON"
            width={300}
            height={300}
          />
        </div>
      </section>
    </main>
  );
}